/**
 * A Theme is a set of options that will be applied
 * ontop of the default values. see options.js for possible options
 */
import { Theme, WP, HOME } from './settings/theme.js';

export default [

 Theme({
    name: 'Catppuccin Macchiato',
    icon: '󰄛 ',

    "spacing": 2,
    "padding": 7,
    "radii": 5,
    "popover_padding_multiplier": 1.4,
    "misc.pywal.theme": "base16-seti",
    "misc.gtk.theme": "Catppuccin-Macchiato-Standard-Mauve-Dark",
    "misc.gtkIcons.theme": "Catppuccin-Macchiato",
    "color.red": "#F38BA8",
    "color.green": "#A6E3A1",
    "color.yellow": "#F9E2AF",
    "color.moon": "#F9E2AF",
    "color.blue": "#89B4FA",
    "color.temp": "#F38BA8",
    "color.download": "#A6E3A1",
    "color.cpucolor": "#F9E2AF",
    "color.upload": "#89B4FA",
    "color.magenta": "#CBA6F7",
    "color.teal": "#94E2D5",
    "color.orange": "#FAB387",
    "color.playcolor": "#FAB387",
    "theme.scheme": "dark",
    "theme.bg": "#181825",
    "theme.fg": "#CDD6F4",
    "theme.accent.accent": "$magenta",
    "theme.accent.fg": "$bg-color",
    "theme.accent.gradient": "to right, $accent, lighten(#D2AC31, 20%)",
    "theme.widget.bg": "$fg-color",
    "theme.widget.opacity": 94,
    "border.color.": "$teal",
    "border.opacity": 100,
    "border.width": 2,
    "border.barcolor": "$accent",
    "hypr.inactive_border": "rgba(333333ff)",
    "hypr.wm_gaps": 3,
    "font.font": "Ubuntu Nerd Font",
    "font.mono": "Mononoki Nerd Font",
    "font.size": 13,
    "applauncher.width": 500,
    "applauncher.height": 400,
    "applauncher.icon_size": 32,
    "bar.position": "top",
    "bar.style": "floating",
    "bar.flat_buttons": true,
    "bar.separators": false,
    "bar.icon": "/home/wilwe/.hyprland.conf/screens/cat.png",
    "battery.bar.width": 50,
    "battery.bar.height": 14,
    "battery.low": 15,
    "battery.medium": 35,
    "desktop.wallpaper.fg": "#fff",
    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/screens/wallpaper.png",
    "desktop.avatar": "/var/lib/AccountsService/icons/wilwe",
    "desktop.drop_shadow": false,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "notifications.black_list": [
      "Spotify"
    ],
    "notifications.position": [
      "top"
    ],
    "notifications.width": 450,
    "dashboard.sys_info_size": 70,
    "mpris.black_list": [
      "Caprine"
    ],
    "mpris.preferred": "spotify",
    "workspaces": 5,
  }),

 Theme({
    name: 'Catppuccin Latte',
    icon: '󰄛 ',

    "spacing": 2,
    "padding": 7,
    "radii": 5,
    "popover_padding_multiplier": 1.4,
    "misc.pywal.theme": "base16-seti",
    "misc.gtk.theme": "Catppuccin-Latte-Standard-Blue-Light",
    "misc.gtkIcons.theme": "Catppuccin-Latte",
    "color.red": "#FF8B47",
    "color.green": "#00ce12",
    "color.yellow": "#9d6c00",
    "color.moon": "#F9E2AF",
    "color.blue": "#0051d5",
    "color.temp": "#FF8B47",
    "color.download": "#00ce12",
    "color.cpucolor": "#9d6c00",
    "color.upload": "#0051d5",
    "color.magenta": "#CBA6F7",
    "color.teal": "#94E2D5",
    "color.orange": "#FAB387",
    "color.playcolor": "#FAB387",
    "theme.scheme": "light",
    "theme.bg": "#F1ECFA",
    "theme.fg": "#452C1F",
    "theme.accent.accent": "#E1A55F",
    "theme.accent.fg": "$bg-color",
    "theme.accent.gradient": "to right, $accent, lighten(#C88F64, 20%)",
    "theme.widget.bg": "$fg-color",
    "theme.widget.opacity": 94,
    "border.color.": "$orange",
    "border.opacity": 100,
    "border.width": 2,
    "border.barcolor": "$accent",
    "hypr.inactive_border": "#FAB387",
    "hypr.wm_gaps": 3,
    "font.font": "Ubuntu Nerd Font",
    "font.mono": "Mononoki Nerd Font",
    "font.size": 13,
    "applauncher.width": 500,
    "applauncher.height": 400,
    "applauncher.icon_size": 32,
    "bar.position": "top",
    "bar.style": "floating",
    "bar.flat_buttons": true,
    "bar.separators": false,
    "bar.icon": "/home/wilwe/.hyprland.conf/screens/cat.png",
    "battery.bar.width": 50,
    "battery.bar.height": 14,
    "battery.low": 15,
    "battery.medium": 35,
    "desktop.wallpaper.fg": "#fff",
    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/screens/wallpaper.png",
    "desktop.avatar": "/var/lib/AccountsService/icons/wilwe",
    "desktop.drop_shadow": false,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "notifications.black_list": [
      "Spotify"
    ],
    "notifications.position": [
      "top"
    ],
    "notifications.width": 450,
    "dashboard.sys_info_size": 70,
    "mpris.black_list": [
      "Caprine"
    ],
    "mpris.preferred": "spotify",
    "workspaces": 5,
  }),

  Theme({
    name: 'Flying Spaghetti Monster',
    icon: '󰄛 ',

    "spacing": 2,
    "padding": 7,
    "radii": 5,
    "popover_padding_multiplier": 1.4,
    "misc.pywal.theme": "base16-seti",
    "misc.gtk.theme": "Catppuccin-Macchiato-Standard-Mauve-Dark",
    "misc.gtkIcons.theme": "Catppuccin-Macchiato",
    "color.red": "#70554A",
    "color.green": "#A6E3A1",
    "color.yellow": "#F9E2AF",
    "color.moon": "#F9E2AF",
    "color.blue": "#89B4FA",
    "color.temp": "#70554A",
    "color.download": "#70554A",
    "color.cpucolor": "#70554A",
    "color.upload": "#70554A",
    "color.magenta": "#CBA6F7",
    "color.teal": "#94E2D5",
    "color.orange": "#FAB387",
    "color.playcolor": "#70554A",
    "theme.scheme": "dark",
    "theme.bg": "#CAB890",
    "theme.fg": "#70554A",
    "theme.accent.accent": "#CAB890",
    "theme.accent.fg": "$bg-color",
    "theme.accent.gradient": "to right, #A58873, lighten(#70554A, 20%)",
    "theme.widget.bg": "#70554A",
    "theme.widget.opacity": 94,
    "border.color.": "$teal",
    "border.opacity": 100,
    "border.width": 2,
    "border.barcolor": "$accent",
    "hypr.inactive_border": "rgba(333333ff)",
    "hypr.wm_gaps": 3,
    "font.font": "Ubuntu Nerd Font",
    "font.mono": "Mononoki Nerd Font",
    "font.size": 13,
    "applauncher.width": 500,
    "applauncher.height": 400,
    "applauncher.icon_size": 32,
    "bar.position": "top",
    "bar.style": "floating",
    "bar.flat_buttons": true,
    "bar.separators": false,
    "bar.icon": "/home/wilwe/.hyprland.conf/screens/spaghetti-monster.png",
    "battery.bar.width": 50,
    "battery.bar.height": 14,
    "battery.low": 15,
    "battery.medium": 35,
    "desktop.wallpaper.fg": "#fff",
    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/screens/spaghetti.png",
    "desktop.avatar": "/home/wilwe/.hyprland.conf/screens/spaghetti-monster.png",
    "desktop.drop_shadow": false,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "notifications.black_list": [
      "Spotify"
    ],
    "notifications.position": [
      "top"
    ],
    "notifications.width": 450,
    "dashboard.sys_info_size": 70,
    "mpris.black_list": [
      "Caprine"
    ],
    "mpris.preferred": "spotify",
    "workspaces": 5,
  }),
];


