/**
 * A Theme is a set of options that will be applied
 * ontop of the default values. see options.js for possible options
 */
import { Theme, WP } from './settings/theme.js';

export default [

 Theme({
    name: 'Catppuccin Macchiato',
    icon: "/home/wilwe/.hyprland.conf/icons/cat.png",

    "spacing": 2,
    "padding": 7,
    "radii": 7,
    "popover_padding_multiplier": 1.4,
    "misc.pywal.theme": "base16-seti",
    "misc.gtk": "Catppuccin-Macchiato-Standard-Mauve-Dark",
    "misc.gtkIcons": "Catppuccin-Macchiato",
    "misc.cursor": "Future-dark-cursors",
    "misc.cursor": "Future-dark-cursors",
    "color.red": "#F38BA8",
    "color.green": "#A6E3A1",
    "color.yellow": "#F9E2AF",
    "color.moon": "#F9E2AF",
    "color.blue": "#89B4FA",
    "color.temp": "#F38BA8",
    "color.download": "#A6E3A1",
    "color.cpucolor": "#F9E2AF",
    "color.upload": "#89B4FA",
    "color.magenta": "#CBA6F7",
    "color.teal": "#94E2D5",
    "color.orange": "#FAB387",
    "color.playcolor": "#FAB387",
    "theme.scheme": "dark",
    "theme.bg": "#181825",
    "theme.fg": "#CDD6F4",
    "theme.accent.accent": "#CBA6F7",
    "hypr.active_border": "rgba(CBA6F7FF) rgba(CBA6F7FF) rgba(89B4FAFF) 45deg",
    "theme.accent.fg": "$bg-color",
    "theme.accent.gradient": "to right, $accent, darken($accent, 20)",
    "theme.accent.bgradient": "to bottom, $accent, darken($accent, 20)",
    "theme.widget.bg": "$fg-color",
    "theme.widget.opacity": 94,
    "bar.mode": "transparent",
 	"bar.border": false,
 	"bar.start.border": true,
 	"bar.start.colormode": "linear-gradient",
 	"bar.start.color": "to left top, $bg-color, darken($accent, 40)",
 	"bar.center.border": true,
 	"bar.center.colormode": "linear-gradient",
 	"bar.center.color": "to top, $bg-color, darken($accent, 40)",
 	"bar.end.border": true,
 	"bar.end.colormode": "linear-gradient",
 	"bar.end.color": "to right top, $bg-color, darken($accent, 40)",
 	"bar.icon": "/home/wilwe/.hyprland.conf/icons/cat.png",
 	"bar.decorsw": false,
 	"grub.theme": 'Arcade',
    "starship.format": "[🭃](#181825)$username[🭟](#181825)[ ]()[🭃](#181825)$directory[🭟](#181825)[ ]()[🭃](#CBA6F7)$time[🭟](#CBA6F7)[ ]()",
    "starship.username.bg": "#181825",
    "starship.username.fg": "#CDD6F4",
    "starship.directory.bg": "#181825",
    "starship.directory.fg": "#CDD6F4",
    "starship.time.bg": "#CBA6F7",
    "starship.time.fg": "#181825",
    //widgets
    "clock.main": '%H:%M',
    "clock.monofont": 'Concert One Mono',
    "clock.fontsize": 90,
    "clock.color": '#dbb5ff',
    "clock.shadow": '6px 8px 0px #AB67E4',
    "clock.anchor": ["top", "right"],
    "clock.margins": ["140", "100"],
    "clock.visible": true,
    "moon.visible": false,
    "music.visible": true,
    "music.anchor": ["bottom","right"],
    "music.margins": ["360","20"],
    "music.layer": "background",
    "music.box": 'transparent',
    "music.border": false,
    "music.footer.positon": false,
    "music.min_width": 600,
    "music.min_height": 162,
    "music.cover_width": 288,
    "music.cover_height": 162,
    "border.color.": "#0000FB",
    "border.opacity": 100,
    "border.width": 2,
    "border.barcolor": "$accent",
    "hypr.inactive_border": "rgba(333333ff)",
    "hypr.wm_gaps": 3,
    "font.font": "Ubuntu Nerd Font",
    "font.mono": "Mononoki Nerd Font",
    "font.size": 13,
    "applauncher.width": 500,
    "applauncher.height": 400,
    "applauncher.icon_size": 32,
    "applauncher.bg": 'linear-gradient',
    "applauncher.bg_color": '135deg,darken($accent, 50), lighten($bg-color,10), $bg-color',
    "applauncher.side": 'player',
    "dashboard.bg": 'linear-gradient',
    "dashboard.bg_color": 'darken($accent, 50), lighten($bg-color,10), $bg-color',
    "quickSettings.bg": 'linear-gradient',
    "quickSettings.bg_color": 'darken($accent, 50), lighten($bg-color,10), $bg-color',
    "bar.position": "top",
    "bar.style": "floating",
    "bar.flat_buttons": true,
    "bar.separators": false,
    "bar.icon": "/home/wilwe/.hyprland.conf/icons/cat.png",
    "battery.bar.width": 50,
    "battery.bar.height": 14,
    "battery.low": 15,
    "battery.medium": 35,
    "desktop.wallpaper.fg": "#fff",
    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/main.png",
    "desktop.avatar": "/var/lib/AccountsService/icons/wilwe",
    "desktop.drop_shadow": false,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "notifications.black_list": [
      "Spotify"
    ],
    "notifications.position": [
      "top"
    ],
    "notifications.width": 450,
    "dashboard.sys_info_size": 70,
    "mpris.preferred": "spotify",
    "workspaces": 5,
  }),

 Theme({
    "misc.cursor": "Future-dark-cursors",
    name: 'Catppuccin Latte',
    icon: "/home/wilwe/.hyprland.conf/icons/cat.png",

    "spacing": 2,
    "padding": 7,
    "radii": 7,
    "popover_padding_multiplier": 1.4,
    "misc.pywal.theme": "base16-seti",
    "misc.gtk": "Catppuccin-Latte-Standard-Blue-Light",
    "misc.gtkIcons": "Catppuccin-Latte",
    "misc.cursor": "Future-dark-cursors",
    "color.red": "#3CB6B6",
    "color.green": "#00ce12",
    "color.yellow": "#9d6c00",
    "color.moon": "#F9E2AF",
    "color.blue": "#0051d5",
    "color.temp": "#FF8B47",
    "color.download": "#00ce12",
    "color.cpucolor": "#9d6c00",
    "color.upload": "#0051d5",
    "color.magenta": "#CBA6F7",
    "color.teal": "#94E2D5",
    "color.orange": "#FAB387",
    "color.playcolor": "#3CB6B6",
    "theme.scheme": "light",
    "theme.bg": "#F1ECFA",
    "theme.fg": "#452C1F",
    "theme.accent.accent": "#4DB0DD",
    "hypr.active_border": "rgba(4DB0DDFF)",
    "theme.accent.fg": "$bg-color",
    "theme.accent.gradient": "to right, $accent, lighten(#35ADAE, 20%)",
    "theme.accent.bgradient": "to bottom, $accent, lighten(#35ADAE, 20%)",
    "theme.widget.bg": "$fg-color",
    "theme.widget.opacity": 94,
    "bar.decorsw": false,
    "starship.format": "[🭃](#F1ECFA)$username[🭟](#F1ECFA)[ ]()[🭃](#F1ECFA)$directory[🭟](#F1ECFA)[ ]()[🭃](#4DB0DD)$time[🭟](#4DB0DD)[ ]()",
    "starship.username.bg": "#F1ECFA",
    "starship.username.fg": "#452C1F",
    "starship.directory.bg": "#F1ECFA",
    "starship.directory.fg": "#452C1F",
    "starship.time.bg": "#4DB0DD",
    "starship.time.fg": "#F1ECFA",
    "clock.main": '%H:%M',
    "clock.monofont": 'Concert One Mono',
    "clock.fontsize": 91,
    "clock.color": '#f0fdff',
    "clock.shadow": "5px 5px 3px #000000",
    "clock.anchor": ["top", "right"],
    "clock.margins": ["120", "90"],
    "clock.visible": true,
    "moon.visible": false,
    "music.visible": true,
    "music.anchor": ["bottom","left"],
    "music.margins": ["30","250"],
    "music.box": "transparent",
    "music.border": false,
    "music.volume": false,
    "music.vertical": true,
    "music.footer.positon": false,
    "music.text.color": "darken($accent, 20)",
    "music.min_width": 450,
    "music.min_height": 80,
    "music.cover_width": 220,
    "music.cover_height": 120,
    "border.color.": "$orange",
    "border.opacity": 100,
    "border.width": 2,
    "border.barcolor": "$accent",
    "hypr.inactive_border": "#FAB387",
    "hypr.wm_gaps": 3,
    "font.font": "Ubuntu Nerd Font",
    "font.mono": "Mononoki Nerd Font",
    "font.size": 13,
    "applauncher.width": 500,
    "applauncher.height": 400,
    "applauncher.icon_size": 32,
    "applauncher.bg": "linear-gradient",
	"applauncher.bg_color": "darken($accent, 10) 0%,$bg-color 20%",
	"applauncher.side": "player",
    "bar.position": "top",
    "bar.style": "floating",
    "bar.mode": "radial-gradient",
	"bar.color": "darken($accent, 5) 10%, $bg-color 50%",
	"bar.decor": false,
    "bar.flat_buttons": true,
    "bar.separators": false,
    "bar.icon": "/home/wilwe/.hyprland.conf/icons/cat.png",
    "battery.bar.width": 50,
    "battery.bar.height": 14,
    "battery.low": 15,
    "battery.medium": 35,
    "desktop.wallpaper.fg": "#fff",
    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/mainwhite.png",
    "desktop.avatar": "/var/lib/AccountsService/icons/wilwe",
    "desktop.wallpaper.transition": "--transition-type wave --transition-angle 225",
    "desktop.drop_shadow": false,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "quickSettings.bg": "linear-gradient",
	"quickSettings.bg_color": "darken($accent, 10) 0%,$bg-color 20%",
    "PowerMenu.bg": "linear-gradient",
	"PowerMenu.bg_color": "darken($accent, 10) 0%,$bg-color 20%",
    "notifications.black_list": [
      "Spotify"
    ],
    "notifications.position": [
      "top"
    ],
    "notifications.width": 450,
    "dashboard.sys_info_size": 70,
    "dashboard.bg": "linear-gradient",
	"dashboard.bg_color": "darken($accent, 10) 0%,$bg-color 20%",
    "mpris.preferred": "spotify",
    "workspaces": 5,
  }),

  Theme({
    name: 'Flying Spaghetti Monster',
    icon: "/home/wilwe/.hyprland.conf/icons/spaghetti-monster.png",

    "spacing": 2,
    "padding": 7,
    "radii": 7,
    "popover_padding_multiplier": 1.4,
    "misc.pywal.theme": "base16-seti",
    "misc.gtk": "Catppuccin-Macchiato-Standard-Mauve-Dark",
    "misc.gtkIcons": "Catppuccin-Macchiato",
    "misc.cursor": "Future-dark-cursors",
    "color.red": "#70554A",
    "color.green": "#A6E3A1",
    "color.yellow": "#F9E2AF",
    "color.moon": "#F9E2AF",
    "color.blue": "#89B4FA",
    "color.temp": "#70554A",
    "color.download": "#70554A",
    "color.cpucolor": "#70554A",
    "color.upload": "#70554A",
    "color.magenta": "#CBA6F7",
    "color.teal": "#94E2D5",
    "color.orange": "#FAB387",
    "color.playcolor": "#70554A",
    "theme.scheme": "dark",
    "theme.bg": "#D3C5AA",
    "theme.fg": "#70554A",
    "theme.accent.accent": "#D3C5AA",
    "hypr.active_border": "rgba(D3C5AAFF)",
    "theme.accent.fg": "$bg-color",
    "theme.accent.gradient": "to right, #A58873, lighten(#70554A, 20%)",
    "theme.accent.bgradient": "to bottom, #A58873, lighten(#70554A, 20%)",
    "theme.widget.bg": "#70554A",
    "theme.widget.opacity": 94,
    "bar.decorsw": true,
    "bar.decorator1": "/home/wilwe/.hyprland.conf/icons/meatball.png",
    "bar.decorator2": "/home/wilwe/.hyprland.conf/icons/meatball.png",
    "bar.dsize": '180%',
    "bar.mode": 'transparent',
    "bar.border": false,
    "bar.start.border": true,
    "bar.start.colormode": 'solid',
    "bar.center.border": true,
    "bar.center.colormode": 'solid',
    "bar.end.border": true,
    "bar.end.colormode": 'solid',
    "grub.theme": "gtg",
    "starship.format": "[🭃](#D3C5AA)$username[🭟](#D3C5AA)[ ]()[🭃](#D3C5AA)$directory[🭟](#D3C5AA)[ ]()[🭃](#D3C5AA)$time[🭟](#D3C5AA)[ ]()",
    "starship.username.bg": "#D3C5AA",
    "starship.username.fg": "#70554A",
    "starship.directory.bg": "#D3C5AA",
    "starship.directory.fg": "#70554A",
    "starship.time.bg": "#D3C5AA",
    "starship.time.fg": "#70554A",
    "clock.visible": true,
    "clock.main": "%H         %M",
    "clock.monofont": "Concert One Mono",
    "clock.fontsize": 69,
    "clock.color": "$accent",
    "clock.shadow": "2px 2px 0px #000000",
    "clock.anchor": ["top", "right"],
    "clock.margins": ["395", "270"],
    "moon.visible": false,
	"music.visible": true,
	"music.anchor": ["top","right"],
	"music.margins": ["220","340"],
	"music.box": "transparent",
	"music.border": false,
	"music.volume": false,
	"music.titlejustification": 'center',
	"music.artistjustification": 'center',
	"music.cover.visible": false,
	"music.footer.positon": false,
	"music.min_width": 370,
	"music.min_height": 210,
	"music.cover_width": 150,
	"music.cover_height": 150,
	"music.text.color": '$bg-color',
    "border.color.": "#0000FB",
    "border.opacity": 100,
    "border.width": 2,
    "border.barcolor": "#91725C",
    "hypr.inactive_border": "rgba(333333ff)",
    "hypr.wm_gaps": 3,
    "font.font": "Ubuntu Nerd Font",
    "font.mono": "Mononoki Nerd Font",
    "font.size": 13,
    "applauncher.width": 500,
    "applauncher.height": 400,
    "applauncher.icon_size": 32,
    "bar.position": "top",
    "bar.style": "floating",
    "bar.flat_buttons": true,
    "bar.separators": false,
    "bar.icon": "/home/wilwe/.hyprland.conf/icons/spaghetti-monster.png",
    "battery.bar.width": 50,
    "battery.bar.height": 14,
    "battery.low": 15,
    "battery.medium": 35,
    "desktop.wallpaper.fg": "#fff",
    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/spaghetti.png",
    "desktop.avatar": "/home/wilwe/.hyprland.conf/icons/spaghetti-monster.png",
    "desktop.wallpaper.transition": "--transition-type center",
    "desktop.drop_shadow": false,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "notifications.black_list": [
      "Spotify"
    ],
    "notifications.position": [
      "top"
    ],
    "notifications.width": 450,
    "dashboard.sys_info_size": 70,
    "mpris.preferred": "spotify",
    "workspaces": 5,
  }),
  
  Theme({
    name: 'My Little Pony',
    icon: "/home/wilwe/.hyprland.conf/icons/fluttershy.png",

    "spacing": 2,
    "padding": 7,
    "radii": 7,
    "popover_padding_multiplier": 1.4,
    "misc.pywal.theme": "base16-seti",
    "misc.gtk": "Catppuccin-Macchiato-Standard-Mauve-Dark",
    "misc.gtkIcons": "Catppuccin-Macchiato",
    "misc.cursor": "Future-dark-cursors",
    "color.red": "#ED488D",
    "color.green": "#67BD52",
    "color.yellow": "#FFF9B1",
    "color.moon": "#FFF9B1",
    "color.blue": "#A2DBF8",
    "color.temp": "#F38BA8",
    "color.download": "#A6E3A1",
    "color.cpucolor": "#F9E2AF",
    "color.upload": "#A2DBF8",
    "color.magenta": "#C8A2C9",
    "color.teal": "#83B9E7",
    "color.orange": "#FCBA64",
    "color.playcolor": "#FCBA64",
    "theme.scheme": "dark",
    "theme.bg": "#35325D",
    "theme.fg": "#F9FAFC",
    "theme.accent.accent": "$magenta",
    "hypr.active_border": "rgba(C8A2C9FF)",
    "theme.accent.fg": "$bg-color",
    "theme.accent.gradient": "to right, #ED4E91, #F8B9D4",
    "theme.accent.bgradient": "to bottom, #ED4E91, #F8B9D4",
    "theme.widget.bg": "$fg-color",
    "theme.widget.opacity": 94,
    "bar.decorsw": true,
    "bar.decorator1": "/home/wilwe/.hyprland.conf/icons/pinky.png",
    "bar.decorator2": "/home/wilwe/.hyprland.conf/icons/pinky2.png",
    "bar.dsize": '180%',
    "starship.format": "[🭃](#35325D)$username[🭟](#35325D)[ ]()[🭃](#35325D)$directory[🭟](#35325D)[ ]()[🭃](#C8A2C9)$time[🭟](#C8A2C9)[ ]()",
    "starship.username.bg": "#35325D",
    "starship.username.fg": "#F9FAFC",
    "starship.directory.bg": "#35325D",
    "starship.directory.fg": "#F9FAFC",
    "starship.time.bg": "#C8A2C9",
    "starship.time.fg": "#35325D",
    "clock.visible": false,
    "moon.visible": false,
    "border.color.": "#0000FB",
    "border.opacity": 100,
    "border.width": 2,
    "border.barcolor": "$accent",
    "hypr.inactive_border": "rgba(333333ff)",
    "hypr.wm_gaps": 3,
    "font.font": "Ubuntu Nerd Font",
    "font.mono": "Mononoki Nerd Font",
    "font.size": 13,
    "applauncher.width": 500,
    "applauncher.height": 400,
    "applauncher.icon_size": 32,
    "bar.position": "top",
    "bar.style": "floating",
    "bar.flat_buttons": true,
    "bar.separators": false,
    "bar.icon": "/home/wilwe/.hyprland.conf/icons/fluttershy.png",
    "battery.bar.width": 50,
    "battery.bar.height": 14,
    "battery.low": 15,
    "battery.medium": 35,
    "desktop.wallpaper.fg": "#fff",
    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/pony.png",
    "desktop.avatar": "/home/wilwe/.hyprland.conf/icons/fluttershy.png",
    "desktop.drop_shadow": false,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "notifications.black_list": [
      "Spotify"
    ],
    "notifications.position": [
      "top"
    ],
    "notifications.width": 450,
    "dashboard.sys_info_size": 70,
    "mpris.preferred": "spotify",
    "workspaces": 5,
  }),
  
  Theme({
    name: 'Pacman',
    icon: "/home/wilwe/.hyprland.conf/icons/ghost.png",

    "spacing": 2,
    "padding": 7,
    "radii": 7,
    "popover_padding_multiplier": 1.4,
    "misc.pywal.theme": "base16-seti",
    "misc.gtk": "Catppuccin-Macchiato-Standard-Mauve-Dark",
    "misc.gtkIcons": "Catppuccin-Macchiato",
    "misc.cursor": "Future-dark-cursors",
    "color.red": "#FF0066",
    "color.green": "#A6E3A1",
    "color.yellow": "#FDFE02",
    "color.moon": "#FDFE02",
    "color.blue": "#03FCD7",
    "color.temp": "#FF0066",
    "color.download": "#A6E3A1",
    "color.cpucolor": "#FDFE02",
    "color.upload": "#03FCD7",
    "color.magenta": "#FEA3F3",
    "color.teal": "#03FCD7",
    "color.orange": "#FDBC42",
    "color.playcolor": "#FDBC42",
    "theme.scheme": "dark",
    "theme.bg": "#181825",
    "theme.fg": "#CDD6F4",
    "theme.accent.accent": "#0000FB",
    "hypr.active_border": "rgba(0000FBFF)",
    "theme.accent.fg": "$bg-color",
    "theme.accent.gradient": "to right, $accent, lighten(#FDFE02, 10%)",
    "theme.accent.bgradient": "to bottom, $accent, lighten(#FDFE02, 10%)",
    "theme.widget.bg": "$fg-color",
    "theme.widget.opacity": 94,
    "bar.decorsw": true,
    "bar.decorator1": "/home/wilwe/.hyprland.conf/icons/ghost.png",
    "bar.decorator2": "/home/wilwe/.hyprland.conf/icons/ghost2.png",
    "bar.dsize": '165%',
    "starship.format": "[🭃](#0000FB)$username[🭟](#0000FB)[ ]()[🭃](#181825)$directory[🭟](#181825)[ ]()[🭃](#0000FB)$time[🭟](#0000FB)[ ]()",
    "starship.username.bg": "#0000FB",
    "starship.username.fg": "#181825",
    "starship.directory.bg": "#181825",
    "starship.directory.fg": "#CDD6F4",
    "starship.time.bg": "#0000FB",
    "starship.time.fg": "#181825",
    "clock.visible": false,
    "moon.visible": false,
    "border.color.": "#0000FB",
    "border.opacity": 100,
    "border.width": 3,
    "border.barcolor": "#0000FB",
    "hypr.inactive_border": "rgba(0000fbff)",
    "hypr.wm_gaps": 3,
    "font.font": "Ubuntu Nerd Font",
    "font.mono": "Mononoki Nerd Font",
    "font.size": 13,
    "applauncher.width": 500,
    "applauncher.height": 400,
    "applauncher.icon_size": 32,
    "bar.position": "top",
    "bar.style": "floating",
    "bar.flat_buttons": true,
    "bar.separators": false,
    "bar.icon": "/home/wilwe/.hyprland.conf/icons/pacman.png",
    "battery.bar.width": 50,
    "battery.bar.height": 14,
    "battery.low": 15,
    "battery.medium": 35,
    "desktop.wallpaper.fg": "#fff",
    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/pacman.png",
    "desktop.avatar": "/home/wilwe/.hyprland.conf/icons/ghost.png",
    "desktop.drop_shadow": false,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "notifications.black_list": [
      "Spotify"
    ],
    "notifications.position": [
      "top"
    ],
    "notifications.width": 450,
    "dashboard.sys_info_size": 70,
    "mpris.preferred": "spotify",
    "workspaces": 5,
  }),
  
  Theme({
    name: 'Weirdmagedon',
    icon: "/home/wilwe/.hyprland.conf/icons/eye.png",

    "spacing": 2,
    "padding": 7,
    "radii": 7,
    "popover_padding_multiplier": 1.4,
    "misc.pywal.theme": "base16-seti",
    "misc.gtk": "Catppuccin-Macchiato-Standard-Mauve-Dark",
    "misc.gtkIcons": "Catppuccin-Macchiato",
    "misc.cursor": "Future-dark-cursors",
    "color.red": "#ECEA79",
    "color.green": "#A6E3A1",
    "color.yellow": "#ECEA79",
    "color.moon": "#ECEA79",
    "color.blue": "#89B4FA",
    "color.temp": "#ECEA79",
    "color.download": "#ECEA79",
    "color.cpucolor": "#ECEA79",
    "color.upload": "#ECEA79",
    "color.magenta": "#CBA6F7",
    "color.teal": "#94E2D5",
    "color.orange": "#ECEA79",
    "color.playcolor": "#ECEA79",
    "theme.scheme": "dark",
    "theme.bg": "#181825",
    "theme.fg": "#ECEA79",
    "theme.accent.accent": "#ECEA79",
    "hypr.active_border": "rgba(ECEA79FF)",
    "theme.accent.fg": "#88303E",
    "theme.accent.gradient": "to right, $accent, lighten(#ECEA79, 20%)",
    "theme.accent.bgradient": "to bottom, $accent, lighten(#ECEA79, 20%)",
    "theme.widget.bg": "$fg-color",
    "theme.widget.opacity": 94,
    "bar.decorsw": true,
    "bar.decorator1": "/home/wilwe/.hyprland.conf/icons/waddles.png",
    "bar.decorator2": "/home/wilwe/.hyprland.conf/icons/waddles2.png",
    "bar.dsize": '180%',
    "starship.format": "[🭃](#181825)$username[🭟](#181825)[ ]()[🭃](#181825)$directory[🭟](#181825)[ ]()[🭃](#ECEA79)$time[🭟](#ECEA79)[ ]()",
    "starship.username.bg": "#181825",
    "starship.username.fg": "#ECEA79",
    "starship.directory.bg": "#181825",
    "starship.directory.fg": "#ECEA79",
    "starship.time.bg": "#ECEA79",
    "starship.time.fg": "#88303E",
    "clock.main": '%H:%M',
    "clock.monofont": 'DigitalDisplay Mono',
    "clock.fontsize": 33,
    "clock.color": '#6C4933',
    "clock.shadow": '0px 0px 0px #FFFFFF',
    "clock.anchor": ['top', 'right'],
    "clock.margins": ["248","940"],
    "clock.visible": true,
    "moon.visible": false,
    "border.color.": "#ECEA79",
    "border.opacity": 100,
    "border.width": 2,
    "border.barcolor": "#ECEA79",
    "hypr.inactive_border": "rgba(333333ff)",
    "hypr.wm_gaps": 3,
    "font.font": "Ubuntu Nerd Font",
    "font.mono": "Mononoki Nerd Font",
    "font.size": 13,
    "applauncher.width": 500,
    "applauncher.height": 400,
    "applauncher.icon_size": 32,
    "bar.position": "top",
    "bar.style": "floating",
    "bar.flat_buttons": true,
    "bar.separators": false,
    "bar.icon": "/home/wilwe/.hyprland.conf/icons/eye.png",
    "battery.bar.width": 50,
    "battery.bar.height": 14,
    "battery.low": 15,
    "battery.medium": 35,
    "desktop.wallpaper.fg": "#fff",
    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/bill.png",
    "desktop.avatar": "/home/wilwe/.hyprland.conf/icons/bill.png",
    "desktop.wallpaper.transition": "--transition-type grow --invert-y --transition-pos 915,280",
    "desktop.drop_shadow": false,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "notifications.black_list": [
      "Spotify"
    ],
    "notifications.position": [
      "top"
    ],
    "notifications.width": 450,
    "dashboard.sys_info_size": 70,
    "mpris.preferred": "spotify",
    "workspaces": 5,
  }),
  
  Theme({
    name: 'Kraina Grzybów',
    icon: "/home/wilwe/.hyprland.conf/icons/grzyb.png",

    "spacing": 2,
    "padding": 7,
    "radii": 7,
    "popover_padding_multiplier": 1.4,
    "misc.pywal.theme": "base16-seti",
    "misc.gtk": "Catppuccin-Macchiato-Standard-Mauve-Dark",
    "misc.gtkIcons": "Catppuccin-Macchiato",
    "misc.cursor": "Future-dark-cursors",
    "color.red": "#DA8D71",
    "color.green": "#A6E3A1",
    "color.yellow": "#FAE0C7",
    "color.moon": "#FAE0C7",
    "color.blue": "#DA8D71",
    "color.temp": "#FFFFFF",
    "color.download": "#FFFFFF",
    "color.cpucolor": "#FFFFFF",
    "color.upload": "#FFFFFF",
    "color.magenta": "#CBA6F7",
    "color.teal": "#94E2D5",
    "color.orange": "#DA8D71",
    "color.playcolor": "#DA8D71",
    "theme.scheme": "dark",
    "theme.bg": "#4D3263",
    "theme.fg": "#FFFFFF",
    "theme.accent.accent": "#DA8D71",
    "hypr.active_border": "rgba(DA8D71FF)",
    "theme.accent.fg": "#FFFFFF",
    "theme.accent.gradient": "to right, $accent, $accent",
    "theme.accent.bgradient": "to bottom, $accent, $accent",
    "theme.widget.bg": "$fg-color",
    "theme.widget.opacity": 94,
    "bar.decorsw": false,
    "bar.dsize": '0%',
    "starship.format": "[🭃](#4D3263)$username[🭟](#4D3263)[ ]()[🭃](#4D3263)$directory[🭟](#4D3263)[ ]()[🭃](#DA8D71)$time[🭟](#DA8D71)[ ]()",
    "starship.username.bg": "#4D3263",
    "starship.username.fg": "#FFFFFF",
    "starship.directory.bg": "#4D3263",
    "starship.directory.fg": "#FFFFFF",
    "starship.time.bg": "#DA8D71",
    "starship.time.fg": "#FFFFFF",
    "moon.path": "/home/wilwe/.hyprland.conf/wallpapers/kgmoon/",
    "clock.visible": false,
    "moon.visible": true,
    "moon.anchor": ['top', 'right'],
    "moon.margins": ['179', '897'],
    "moon.size": '300px',
    "border.color.": "#ECEA79",
    "border.opacity": 100,
    "border.width": 2,
    "border.barcolor": "$accent",
    "hypr.inactive_border": "rgba(333333ff)",
    "hypr.wm_gaps": 3,
    "font.font": "Ubuntu Nerd Font",
    "font.mono": "Mononoki Nerd Font",
    "font.size": 13,
    "applauncher.width": 500,
    "applauncher.height": 400,
    "applauncher.icon_size": 32,
    "bar.position": "top",
    "bar.style": "floating",
    "bar.flat_buttons": true,
    "bar.separators": false,
    "bar.icon": "/home/wilwe/.hyprland.conf/icons/grzyb.png",
    "battery.bar.width": 50,
    "battery.bar.height": 14,
    "battery.low": 15,
    "battery.medium": 35,
    "desktop.wallpaper.fg": "#fff",
    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/kraina grzybów.png",
    "desktop.avatar": "/var/lib/AccountsService/icons/wilwe",
    "desktop.wallpaper.transition": "--transition-type grow --invert-y --transition-pos 890,320",
    "desktop.drop_shadow": false,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "notifications.black_list": [
      "Spotify"
    ],
    "notifications.position": [
      "top"
    ],
    "notifications.width": 450,
    "dashboard.sys_info_size": 70,
    "mpris.preferred": "spotify",
    "workspaces": 5,
  }),
  
  Theme({
    name: 'Jan Paweł 2',
    icon: "/home/wilwe/.hyprland.conf/icons/kremowka.png",

    "spacing": 2,
    "padding": 7,
    "radii": 7,
    "popover_padding_multiplier": 1.4,
    "misc.pywal.theme": "base16-seti",
    "misc.gtk": "Catppuccin-Macchiato-Standard-Mauve-Dark",
    "misc.gtkIcons": "Catppuccin-Macchiato",
    "misc.cursor": "Future-dark-cursors",
    "color.red": "#ECEA79",
    "color.green": "#A6E3A1",
    "color.yellow": "#ECEA79",
    "color.moon": "#ECEA79",
    "color.blue": "#89B4FA",
    "color.temp": "#ECEA79",
    "color.download": "#ECEA79",
    "color.cpucolor": "#ECEA79",
    "color.upload": "#ECEA79",
    "color.magenta": "#CBA6F7",
    "color.teal": "#94E2D5",
    "color.orange": "#ECEA79",
    "color.playcolor": "#ECEA79",
    "theme.scheme": "dark",
    "theme.bg": "#181825",
    "theme.fg": "#ECEA79",
    "theme.accent.accent": "#ECEA79",
    "hypr.active_border": "rgba(ECEA79FF)",
    "theme.accent.fg": "#88303E",
    "theme.accent.gradient": "to right, $accent, lighten(#ECEA79, 20%)",
    "theme.accent.bgradient": "to bottom, $accent, lighten(#ECEA79, 20%)",
    "theme.widget.bg": "$fg-color",
    "theme.widget.opacity": 94,
    "bar.decorsw": true,
    "bar.decorator1": "/home/wilwe/.hyprland.conf/icons/kremowka.png",
    "bar.decorator2": "/home/wilwe/.hyprland.conf/icons/kremowka.png",
    "bar.dsize": '180%',
    "starship.format": "[🭃](#181825)$username[🭟](#181825)[ ]()[🭃](#181825)$directory[🭟](#181825)[ ]()[🭃](#ECEA79)$time[🭟](#ECEA79)[ ]()",
    "starship.username.bg": "#181825",
    "starship.username.fg": "#ECEA79",
    "starship.directory.bg": "#181825",
    "starship.directory.fg": "#ECEA79",
    "starship.time.bg": "#ECEA79",
    "starship.time.fg": "#88303E",
    "moon.path": "/home/wilwe/.hyprland.conf/wallpapers/kremoon/",
    "clock.visible": false,
    "moon.visible": true,
    "moon.anchor": ['top', 'right'],
    "moon.margins": ['440', '1085'],
    "moon.size": '125px',
    "sound.visible": true,
    "sound.sound": '/home/wilwe/Muzyka/Dość.ogg',
    "sound.anchor": ['bottom', 'right'],
    "sound.margins": ['270', '845'],
    "sound.size": '35',
    "sound.icon": '/home/wilwe/.hyprland.conf/icons/kremowka.png',
    "border.color.": "#ECEA79",
    "border.opacity": 100,
    "border.width": 2,
    "border.barcolor": "$accent",
    "hypr.inactive_border": "rgba(333333ff)",
    "hypr.wm_gaps": 3,
    "font.font": "Ubuntu Nerd Font",
    "font.mono": "Mononoki Nerd Font",
    "font.size": 13,
    "applauncher.width": 500,
    "applauncher.height": 400,
    "applauncher.icon_size": 32,
    "applauncher.label": 'Chowaj dzieci Papież leci\nczy to jest kurwa śmieszne\nTak',
    "bar.position": "top",
    "bar.style": "floating",
    "bar.flat_buttons": true,
    "bar.separators": false,
    "bar.icon": "/home/wilwe/.hyprland.conf/icons/kremowka.png",
    "battery.bar.width": 50,
    "battery.bar.height": 14,
    "battery.low": 15,
    "battery.medium": 35,
    "desktop.wallpaper.fg": "#fff",
    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/papatapeta.png",
    "desktop.avatar": "/home/wilwe/.hyprland.conf/icons/kremowka.png",
    "desktop.wallpaper.transition": "--transition-type center --transition-step 2",
    "desktop.drop_shadow": false,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "notifications.black_list": [
      "Spotify"
    ],
    "notifications.position": [
      "top"
    ],
    "notifications.width": 450,
    "dashboard.sys_info_size": 70,
    "mpris.preferred": "spotify",
    "workspaces": 5,
  }),
  
  Theme({
    name: 'Freddy Fnaf',
    icon: "/home/wilwe/.hyprland.conf/icons/freddy.png",

    "spacing": 2,
    "padding": 7,
    "radii": 7,
    "popover_padding_multiplier": 1.4,
    "misc.pywal.theme": "base16-seti",
    "misc.gtk": "Catppuccin-Macchiato-Standard-Mauve-Dark",
    "misc.gtkIcons": "Catppuccin-Macchiato",
    "misc.cursor": "Future-dark-cursors",
    "color.red": "#ECEA79",
    "color.green": "#A6E3A1",
    "color.yellow": "#ECEA79",
    "color.moon": "#ECEA79",
    "color.blue": "#FEF8EA",
    "color.temp": "#FEF8EA",
    "color.download": "#FEF8EA",
    "color.cpucolor": "#FEF8EA",
    "color.upload": "#FEF8EA",
    "color.magenta": "#CBA6F7",
    "color.teal": "#94E2D5",
    "color.orange": "#A16437",
    "color.playcolor": "#A16437",
    "theme.scheme": "dark",
    "theme.bg": "#181825",
    "theme.fg": "#FEF8EA",
    "theme.accent.accent": "#794935",
    "hypr.active_border": "rgba(794935FF)",
    "theme.accent.fg": "#FFFFFF",
    "theme.accent.gradient": "to right, $accent, lighten($accent, 20%)",
    "theme.accent.bgradient": "to bottom, $accent, lighten($accent, 20%)",
    "theme.widget.bg": "$fg-color",
    "theme.widget.opacity": 94,
    "bar.decorsw": true,
    "bar.decorator1": "/home/wilwe/.hyprland.conf/icons/fnaf.png",
    "bar.decorator2": "/home/wilwe/.hyprland.conf/icons/fnaf.png",
    "bar.dsize": '180%',
    "starship.format": "[🭃](#181825)$username[🭟](#181825)[ ]()[🭃](#181825)$directory[🭟](#181825)[ ]()[🭃](#794935)$time[🭟](#794935)[ ]()",
    "starship.username.bg": "#181825",
    "starship.username.fg": "#FEF8EA",
    "starship.directory.bg": "#181825",
    "starship.directory.fg": "#FEF8EA",
    "starship.time.bg": "#794935",
    "starship.time.fg": "#FFFFFF",
    "clock.main": 'Freddy Fanf',
    "clock.monofont": 'Concert one',
    "clock.fontsize": 40,
    "clock.color": '#FFFFFF',
    "clock.anchor": ['top', 'right'],
    "clock.margins": ['50', '875'],
    "clock.visible": true,
    "moon.visible": false,
    "sound.visible": true,
    "sound.sound": '/home/wilwe/Muzyka/click.mp3',
    "sound.anchor": ['top', 'right'],
    "sound.margins": ['490', '1025'],
    "sound.size": '35',
    "border.color.": "#A16437",
    "border.opacity": 100,
    "border.width": 2,
    "border.barcolor": "#A16437",
    "hypr.inactive_border": "rgba(333333ff)",
    "hypr.wm_gaps": 3,
    "font.font": "Ubuntu Nerd Font",
    "font.mono": "Mononoki Nerd Font",
    "font.size": 13,
    "applauncher.width": 500,
    "applauncher.height": 400,
    "applauncher.icon_size": 32,
    "applauncher.label": 'O cholera czy to\nfreddy fastber\nHar Har Har\nHar Har Har Har',
    "bar.position": "top",
    "bar.style": "floating",
    "bar.flat_buttons": true,
    "bar.separators": false,
    "bar.icon": "/home/wilwe/.hyprland.conf/icons/freddy.png",
    "battery.bar.width": 50,
    "battery.bar.height": 14,
    "battery.low": 15,
    "battery.medium": 35,
    "desktop.wallpaper.fg": "#fff",
    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/freddyfnaf.png",
    "desktop.avatar": "/home/wilwe/.hyprland.conf/icons/freddy.png",
    "desktop.wallpaper.transition": "--transition-type grow --invert-y --transition-pos 865,515",
    "desktop.drop_shadow": false,
    "desktop.shadow": "rgba(0, 0, 0, .6)",
    "notifications.black_list": [
      "Spotify"
    ],
    "notifications.position": [
      "top"
    ],
    "notifications.width": 450,
    "dashboard.sys_info_size": 70,
    "mpris.preferred": "spotify",
    "workspaces": 5,
  }),
  Theme({
    name: 'Fucked',
    icon: '/home/wilwe/.hyprland.conf/icons/meatball.png',
  "spacing": 2,
  "padding": 8,
  "radii": 5,
  "popover_padding_multiplier": 1.4,
  "misc.pywal.theme": "",
  "misc.gtk": "",
  "misc.gtkIcons": "",
  "color.red": "#000000",
  "color.green": "#ffffff",
  "color.yellow": "#f0f0f0",
  "color.moon": "#0f0f0f",
  "color.blue": "#ff00ff",
  "color.temp": "#00ff00",
  "color.download": "#000fff",
  "color.cpucolor": "#fff000",
  "color.upload": "#ff0f0f",
  "color.magenta": "#00f0f0",
  "color.teal": "#000f0f",
  "color.orange": "#fff0f0",
  "color.playcolor": "#fffff0",
  "theme.scheme": "light",
  "theme.bg": "#eeee0e",
  "theme.fg": "#000700",
  "theme.accent.accent": "#666420",
  "hypr.active_border": "rgba(666420FF)",
  "theme.accent.fg": "#666420",
  "theme.accent.gradient": "red,blue",
  "theme.accent.bgradient": "black,red",
  "theme.widget.bg": "#ff2137",
  "theme.widget.opacity": 69,
  "border.color": "magenta",
  "border.opacity": 45,
  "border.width": 14,
  "border.barcolor": "red",
  "hypr.inactive_border": "white",
  "hypr.wm_gaps": 3,
  "font.font": "Hack Nerd Font Bold",
  "font.mono": "D050000L",
  "font.size": 24,
  "applauncher.width": 200,
  "applauncher.height": 100,
  "applauncher.icon_size": 77,
  "applauncher.descvisible": true,
  "applauncher.bg": "repeating-linear-gradient",
  "applauncher.bg_color": "to right,red,red 5px,green 5px,green 10px,blue 10px, blue 11px",
  "applauncher.br_mode": true,
  "applauncher.br_radius": 34,
  "applauncher.br": "$border-width solid #ffffff",
  "applauncher.side": "none",
  "applauncher.labvisible": true,
  "applauncher.icovisible": true,
  "applauncher.avatarvisible": true,
  "applauncher.label": "I use arch btw",
  "applauncher.anchor": [
    "top",
    "left",
    "bottom",
    "right"
  ],
  "applauncher.margins": [
    "420",
    "69"
  ],
  "bar.position": "top",
  "bar.style": "floating",
  "bar.mode": "repeating-linear-gradient",
  "bar.color": "135deg,black, black 5px, white 5px, white 10px, red 10px, red 15px",
  "bar.border": false,
  "bar.start.border": false,
  "bar.start.colormode": "repeating-linear-gradient",
  "bar.start.color": "45deg,blue, blue 5px, red 5px, red 20px",
  "bar.center.border": false,
  "bar.center.colormode": "repeating-radial-gradient",
  "bar.center.color": "red, yellow,blue,green,white,black",
  "bar.end.border": false,
  "bar.end.colormode": "repeating-linear-gradient",
  "bar.end.color": "90deg,red,red 2px,green 2px,green 3px,blue 3px, blue 5px",
  "bar.player_length": 50,
  "bar.flat_buttons": false,
  "bar.separators": true,
  "bar.icon": "/home/wilwe/.hyprland.conf/icons/waddles.png",
  "bar.decorsw": true,
  "bar.dsize": "200%",
  "quickSettings.bg": "repeating-linear-gradient",
  "quickSettings.bg_color": "$bg-color, $bg-color 5px, yellow 5px, yellow 10px, transparent 10px, transparent 30px",
  "quickSettings.br_mode": true,
  "quickSettings.br_radius": 43,
  "quickSettings.br": "$border-width*2 solid $accent",
  "clock.main": "%H:%M",
  "clock.visible": true,
  "clock.font": "D050000L 10",
  "clock.monofont": "D050000L",
  "clock.fontsize": 256,
  "clock.layer": "background",
  "clock.color": "blue",
  "clock.background": "repeating-linear-gradient",
  "clock.bg_color": "red,blue, green,blue",
  "clock.border": true,
  "clock.width": "$clock-size",
  "clock.height": "$clock-size*2",
  "clock.shadow": "20px 69px 0px #fff000",
  "clock.anchor": [
    "top",
    "left"
  ],
  "clock.margins": [
    "210",
    "0"
  ],
  "moon.path": "",
  "moon.visible": false,
  "moon.size": "0",
  "moon.layer": "background",
  "moon.anchor": [
    "top",
    "left"
  ],
  "moon.margins": [
    "0",
    "0"
  ],
  "bgtop.image": "",
  "bgtop.layer": "bottom",
  "bgtop.visible": false,
  "bgtop.size": "0",
  "bgtop.anchor": [
    "top",
    "left"
  ],
  "bgtop.margins": [
    "0",
    "0"
  ],
  "sound.sound": " ",
  "sound.layer": "background",
  "sound.visible": false,
  "sound.size": "0",
  "sound.icon": "",
  "sound.anchor": [
    "top",
    "right"
  ],
  "sound.margins": [
    "0",
    "0"
  ],
  "info.anchor": [
    "bottom",
    "right",
    "left",
    "top"
  ],
  "info.margins": [
    "20",
    "20"
  ],
  "info.bgcolor": "transparentize($bg-color, 0.3)",
  "info.layer": "overlay",
  "music.visible": false,
  "music.anchor": [
    "bottom",
    "right"
  ],
  "music.margins": [
    "20",
    "20"
  ],
  "music.layer": "background",
  "music.box": "blurred",
  "music.box_color": "$bg-color",
  "music.border": true,
  "music.volume": true,
  "music.vertical": false,
  "music.titlejustification": "left",
  "music.artistjustification": "left",
  "music.cover.visible": true,
  "music.cover.hpack": "start",
  "music.footer.positon": true,
  "music.footer.controls": true,
  "music.footer.box_visible": "transparent",
  "music.footer.box_color": "$bg-color",
  "music.footer.border": false,
  "music.text.visible": "transparent",
  "music.text.bg_color": "$bg-color",
  "music.text.color": "$fg-color",
  "music.text.border": false,
  "music.Title": true,
  "music.Artist": true,
  "music.min_width": 500,
  "music.min_height": 200,
  "music.cover_width": 150,
  "music.cover_height": 150,
  "PowerMenu.bg": "repeating-linear-gradient",
  "PowerMenu.bg_color": "69deg,yellow,yellow 25px, blue 25px, blue 30px, red 30px, red 69px",
  "PowerMenu.br_mode": true,
  "PowerMenu.br_radius": 100,
  "PowerMenu.br": "$border-width*5 solid $accent",
  "battery.bar.width": 145,
  "battery.bar.height": 14,
  "battery.low": 93,
  "battery.medium": 103,
  "desktop.wallpaper.fg": "#fff",
  "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/mess.png",
  "desktop.wallpaper.transition": "--transition-type wave --transition-angle 45",
  "desktop.avatar": "/var/lib/AccountsService/icons/wilwe",
  "desktop.drop_shadow": false,
  "desktop.shadow": "rgba(0, 0, 0, .6)",
  "notifications.black_list": [
    "Spotify"
  ],
  "notifications.position": [
    "top"
  ],
  "notifications.width": 450,
  "dashboard.sys_info_size": 70,
  "dashboard.bg": "radial-gradient",
  "dashboard.bg_color": "red,green,black,white,red,red,blue,magenta,red,blue,black",
  "dashboard.br_mode": true,
  "dashboard.br_radius": 50,
  "dashboard.br": "$border-width*2 solid $accent",
  "mpris.black_list": [
    "VLC media player"
  ],
  "mpris.preferred": "librewolf",
  "workspaces": 27,
  "OverView.bg": "repeating-linear-gradient",
  "OverView.bg_color": "red,green,red,green",
  "OverView.br_mode": true,
  "OverView.br_radius": 20,
  "OverView.br": "$border-width solid $accent"
  }),
];


