/**
 * A Theme is a set of options that will be applied
 * ontop of the default values. see options.js for possible options
 */
import { Theme, WP } from './settings/theme.js';

export default [

 Theme({
	    name: 'Skull',
	    icon: "/home/wilwe/.hyprland.conf/icons/cat.png",

	    "padding": 7,
	    "radii": 7,
	    "misc.pywal.theme": "base16-seti",
	    "misc.gtk": "ags",
	    "misc.gtkIcons": "Catppuccin-Macchiato",
	    "misc.cursor": "Future-dark-cursors",
	    "misc.cursor": "Future-dark-cursors",
	    "color.red": "#F38BA8",
	    "color.green": "#A6E3A1",
	    "color.yellow": "#F9E2AF",
	    "color.moon": "#F9E2AF",
	    "color.blue": "#89B4FA",
	    "color.temp": "#F38BA8",
	    "color.download": "#A6E3A1",
	    "color.cpucolor": "#F9E2AF",
	    "color.upload": "#89B4FA",
	    "color.magenta": "#CBA6F7",
	    "color.teal": "#94E2D5",
	    "color.orange": "#FAB387",
	    "color.playcolor": "$green",
	    "theme.bg": "#181825",
	    "theme.fg": "#CDD6F4",
	    "theme.accent.accent": "#CBA6F7",
	    "hypr.active_border": "rgba(CBA6F7FF) rgba(CBA6F7FF) rgba(89B4FAFF) 45deg",
	    "theme.accent.fg": "$bg-color",
	    "theme.accent.gradient": "to right, $accent, darken($accent, 20)",
	    "theme.accent.bgradient": "to bottom, $accent, darken($accent, 20)",
	    "bar.mode": "transparent",
	    "bar.border": false,
	    "bar.start.border": true,
	    "bar.start.colormode": "linear-gradient",
	    "bar.start.color": "to left top, $bg-color, darken($accent, 40)",
	    "bar.center.border": true,
	    "bar.center.colormode": "linear-gradient",
	    "bar.center.color": "to top, $bg-color, darken($accent, 40)",
	    "bar.end.border": true,
	    "bar.end.colormode": "linear-gradient",
	    "bar.end.color": "to right top, $bg-color, darken($accent, 40)",
	    "bar.icon": "/home/wilwe/.hyprland.conf/icons/cat.png",
	    "bar.decorsw": false,
	    "grub.theme": 'Arcade',
	    "starship.format": "[](#000000)[ ](bg:#000000)$username[](bg:$blue fg:#000000)$directory[](bg:$accent fg:$blue)$time[ ]($accent)",
	    "starship.ldec": "",
	    "starship.rdec": "",
	    "starship.username.bg": "#000000",
	    "starship.directory.bg": "$blue",
	    "starship.directory.fg": "$accent-fg",
	    //widgets
	    "clock.main": '%H:%M',
	    "clock.monofont": 'Concert One Mono',
	    "clock.fontsize": 90,
	    "clock.color": '#dbb5ff',
	    "clock.shadow": '6px 8px 0px #AB67E4',
	    "clock.anchor": ["top", "right"],
	    "clock.margins": ["140", "100"],
	    "clock.visible": true,
	    "moon.visible": false,
	    "music.visible": true,
	    "music.anchor": ["bottom","right"],
	    "music.margins": ["360","20"],
	    "music.text.color": "$yellow",
	    "music.layer": "background",
	    "music.box": 'transparent',
	    "music.border": false,
	    "music.footer.positon": false,
	    "music.min_width": 600,
	    "music.min_height": 162,
	    "music.cover_width": 288,
	    "music.cover_height": 162,
	    "border.color.": "#0000FB",
	    "border.opacity": 100,
	    "border.width": 2,
	    "border.barcolor": "$accent",
	    "font.font": "Ubuntu Nerd Font",
	    "font.mono": "Mononoki Nerd Font",
	    "font.size": 13,
	    "applauncher.height": 400,
	    "applauncher.bg": 'linear-gradient',
	    "applauncher.bg_color": '135deg,darken($accent, 50), lighten($bg-color,10), $bg-color',
	    "applauncher.side": 'player',
	    "dashboard.bg": 'linear-gradient',
	    "dashboard.bg_color": 'darken($accent, 50), lighten($bg-color,10), $bg-color',
	    "quickSettings.bg": 'linear-gradient',
	    "quickSettings.bg_color": 'darken($accent, 50), lighten($bg-color,10), $bg-color',
	    "bar.icon": "/home/wilwe/.hyprland.conf/icons/cat.png",
	    "battery.bar.width": 50,
	    "battery.bar.height": 14,
	    "battery.low": 15,
	    "battery.medium": 35,
	    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/main.jpg",
  }),

 Theme({
	    name: 'DeerFox',
	    icon: "/home/wilwe/.hyprland.conf/icons/cat.png",

	    "spacing": 2,
	    "padding": 7,
	    "radii": 7,
	    "popover_padding_multiplier": 1.4,
	    "misc.pywal.theme": "base16-seti",
	    "misc.gtk": "ags",
	    "misc.gtkIcons": "Catppuccin-Latte",
	    "misc.cursor": "Future-dark-cursors",
	    "color.red": "#3CB6B6",
	    "color.green": "#00ce12",
	    "color.yellow": "#9d6c00",
	    "color.moon": "#F9E2AF",
	    "color.blue": "#0051d5",
	    "color.temp": "#FF8B47",
	    "color.download": "#00ce12",
	    "color.cpucolor": "#9d6c00",
	    "color.upload": "#0051d5",
	    "color.magenta": "#CBA6F7",
	    "color.teal": "#94E2D5",
	    "color.orange": "#FAB387",
	    "color.playcolor": "#3CB6B6",
	    "theme.scheme": "light",
	    "theme.bg": "#F1ECFA",
	    "theme.darken_bg": "#e0e0e0",
	    "theme.fg": "#452C1F",
	    "theme.accent.accent": "#4DB0DD",
	    "hypr.active_border": "rgba(4DB0DDFF)",
	    "theme.accent.fg": "$bg-color",
	    "theme.accent.gradient": "to right, $accent, lighten(#35ADAE, 20%)",
	    "theme.accent.bgradient": "to bottom, $accent, lighten(#35ADAE, 20%)",
	    "theme.widget.bg": "$fg-color",
	    "theme.widget.opacity": 94,
	    "bar.decorsw": false,
	    "clock.main": '%H:%M',
	    "clock.monofont": 'Concert One Mono',
	    "clock.fontsize": 91,
	    "clock.color": '#f0fdff',
	    "clock.shadow": "5px 5px 3px #000000",
	    "clock.anchor": ["top", "right"],
	    "clock.margins": ["120", "90"],
	    "clock.visible": true,
	    "moon.visible": false,
	    "music.visible": true,
	    "music.anchor": ["bottom","left"],
	    "music.margins": ["30","250"],
	    "music.box": "transparent",
	    "music.border": false,
	    "music.volume": false,
	    "music.vertical": true,
	    "music.footer.positon": false,
	    "music.text.color": "darken($accent, 20)",
	    "music.min_width": 450,
	    "music.min_height": 80,
	    "music.cover_width": 220,
	    "music.cover_height": 120,
	    "border.color.": "$orange",
	    "border.opacity": 100,
	    "border.width": 2,
	    "border.barcolor": "$accent",
	    "hypr.inactive_border": "#FAB387",
	    "hypr.wm_gaps": 3,
	    "font.font": "Ubuntu Nerd Font",
	    "font.mono": "Mononoki Nerd Font",
	    "font.size": 13,
	    "applauncher.width": 500,
	    "applauncher.height": 400,
	    "applauncher.icon_size": 32,
	    "applauncher.bg": "linear-gradient",
	    "applauncher.bg_color": "darken($accent, 10) 0%,$bg-color 20%",
	    "applauncher.side": "player",
	    "bar.position": "top",
	    "bar.style": "floating",
	    "bar.mode": "radial-gradient",
	    "bar.color": "darken($accent, 5) 10%, $bg-color 50%",
	    "bar.decor": false,
	    "bar.flat_buttons": true,
	    "bar.separators": false,
	    "bar.icon": "/home/wilwe/.hyprland.conf/icons/cat.png",
	    "battery.bar.width": 50,
	    "battery.bar.height": 14,
	    "battery.low": 15,
	    "battery.medium": 35,
	    "desktop.wallpaper.fg": "#fff",
	    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/mainwhite.jpg",
	    "desktop.avatar": "/var/lib/AccountsService/icons/wilwe",
	    "desktop.wallpaper.transition": "--transition-type wave --transition-angle 225",
	    "desktop.drop_shadow": false,
	    "desktop.shadow": "rgba(0, 0, 0, .6)",
	    "quickSettings.bg": "linear-gradient",
	    "quickSettings.bg_color": "darken($accent, 10) 0%,$bg-color 20%",
	    "PowerMenu.bg": "linear-gradient",
	    "PowerMenu.bg_color": "darken($accent, 10) 0%,$bg-color 20%",
  }),

  Theme({
	    name: 'Corn',
	    icon: "/home/wilwe/.hyprland.conf/icons/eye.png",

	    "spacing": 2,
	    "padding": 7,
	    "radii": 7,
	    "popover_padding_multiplier": 1.4,
	    "misc.pywal.theme": "base16-seti",
	    "misc.gtk": "ags",
	    "misc.gtkIcons": "Catppuccin-Macchiato",
	    "misc.cursor": "Future-dark-cursors",
	    "color.red": "#FF2020",
	    "color.green": "#A6E3A1",
	    "color.yellow": "#FF2020",
	    "color.moon": "#FF2020",
	    "color.blue": "#89B4FA",
	    "color.temp": "#FF2020",
	    "color.download": "#FF2020",
	    "color.cpucolor": "#FF2020",
	    "color.upload": "#FF2020",
	    "color.magenta": "#CBA6F7",
	    "color.teal": "#94E2D5",
	    "color.orange": "#FF2020",
	    "color.playcolor": "#FF2020",
	    "theme.scheme": "dark",
	    "theme.bg": "#332229",
	    "theme.fg": "#FF2020",
	    "theme.accent.accent": "#FF2020",
	    "hypr.active_border": "rgba(FF2020FF)",
	    "theme.accent.fg": "#000000",
	    "theme.accent.gradient": "to right, $accent, lighten(#FF2020, 5%)",
	    "theme.accent.bgradient": "to bottom, $accent, lighten(#FF2020, 5%)",
	    "theme.widget.bg": "$fg-color",
	    "theme.widget.opacity": 94,
	    "bar.decorsw": false,
	    "clock.visible": false,
	    "moon.visible": false,
	    "border.color.": "#FF2020",
	    "border.opacity": 100,
	    "border.width": 2,
	    "border.barcolor": "#FF2020",
	    "hypr.inactive_border": "rgba(332229ff)",
	    "hypr.wm_gaps": 3,
	    "font.font": "Ubuntu Nerd Font",
	    "font.mono": "Mononoki Nerd Font",
	    "font.size": 13,
	    "applauncher.width": 500,
	    "applauncher.height": 400,
	    "applauncher.icon_size": 32,
	    "bar.position": "top",
	    "bar.style": "floating",
	    "bar.flat_buttons": true,
	    "bar.separators": false,
	    "bar.icon": "/home/wilwe/.hyprland.conf/icons/eye.png",
	    "battery.bar.width": 50,
	    "battery.bar.height": 14,
	    "battery.low": 15,
	    "battery.medium": 35,
	    "desktop.wallpaper.fg": "#fff",
	    "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/vamp.jpg",
  }),

  Theme({
	  name: "Deer",
	  icon: "/home/wilwe/.hyprland.conf/icons/deer.svg",
	  
	  "misc.gtk": "ags",
	  "misc.gtkIcons": "Catppuccin-Latte",
	  "misc.cursor": "Future-dark-cursors",
	  "border.width": 2,
	  "border.barcolor": "$accent",
	  "hypr.active_border": "rgba(CE8FC5ff)",
	  "hypr.inactive_border": "rgba(77AFD5ff)",
	  "color.red": "#8C4C8A",
	  "color.green": "#94BCB4",
	  "color.yellow": "#afa72b",
	  "color.moon": "$yellow",
	  "color.blue": "#77AFD5",
	  "color.temp": "$red",
	  "color.download": "$green",
	  "color.cpucolor": "$yellow",
	  "color.upload": "$blue",
	  "color.magenta": "#8C4C8A",
	  "color.teal": "#65A7C5",
	  "color.orange": "#C4849C",
	  "color.playcolor": "$orange",
	  "theme.scheme": "light",
	  "theme.bg": "#EEF0F4",
	  "theme.darken_bg": "#c7c8c9",
	  "theme.fg": "#1A4C75",
	  "theme.accent.accent": "#CE8FC5",
	  "starship.format": "$username$directory$time[ ]()",
	  "starship.ldec": "",
	  "starship.rdec": "",
	  "starship.username.bg": "$dark-bg-color",
	  "starship.username.fg": "$fg-color",
	  "starship.directory.bg": "$dark-bg-color",
	  "starship.directory.fg": "$fg-color",
	  "starship.time.bg": "$accent",
	  "starship.time.fg": "$accent-fg",
	  "applauncher.height": 400,
	  "applauncher.bg": "linear-gradient",
	  "applauncher.bg_color": "135deg,lighten($accent, 10), lighten($bg-color,10), $bg-color",
	  "applauncher.br_mode": true,
	  "applauncher.br_radius": 20,
	  "applauncher.br": "$border-width solid $accent",
	  "applauncher.side": "player",
	  "applauncher.labvisible": true,
	  "applauncher.icovisible": true,
	  "bar.mode": "transparent",
	  "bar.color": "$bg-color",
	  "bar.border": false,
	  "bar.start.border": true,
	  "bar.start.colormode": "linear-gradient",
	  "bar.start.color": "to left top, $bg-color, lighten($accent, 10)",
	  "bar.center.border": true,
	  "bar.center.colormode": "linear-gradient",
	  "bar.center.color": "to top, $bg-color, lighten($accent, 10)",
	  "bar.end.border": true,
	  "bar.end.colormode": "linear-gradient",
	  "bar.end.color": "to right top, $bg-color, lighten($accent, 10)",
	  "bar.player_length": 50,
	  "bar.flat_buttons": true,
	  "bar.separators": false,
	  "bar.icon": "/home/wilwe/.hyprland.conf/icons/deer.svg",
	  "bar.decorsw": false,
	  "battery.bar.width": 50,
	  "quickSettings.bg": "linear-gradient",
	  "quickSettings.bg_color": "lighten($accent, 10), lighten($bg-color,10), $bg-color",
	  "quickSettings.br_mode": true,
	  "quickSettings.br_radius": 20,
	  "quickSettings.br": "$border-width solid $accent",
	  "clock.main": "%H:%M",
	  "clock.visible": true,
	  "clock.fontsize": 75,
	  "clock.color": "$bg-color",
	  "clock.shadow": "6px 8px 2px darken($bg-color, 30)",
	  "clock.anchor": [
	    "bottom",
	    "left"
	  ],
	  "clock.margins": [
	    "130",
	    "100"
	  ],
	  "moon.path": "/home/wilwe/.hyprland.conf/wallpapers/winmoon/",
	  "moon.visible": true,
	  "moon.size": "312",
	  "moon.layer": "background",
	  "moon.anchor": [
	    "top",
	    "left"
	  ],
	  "moon.margins": [
	    "92",
	    "839"
	  ],
	  "music.visible": true,
	  "music.anchor": [
	    "bottom",
	    "right"
	  ],
	  "music.margins": [
	    "60",
	    "20"
	  ],
	  "music.box": "transparent",
	  "music.border": false,
	  "music.volume": false,
	  "music.vertical": true,
	  "music.cover.hpack": "center",
	  "music.footer.positon": false,
	  "music.footer.controls": false,
	  "music.text.color": "$bg-color",
	  "music.min_width": 300,
	  "music.min_height": 112,
	  "music.cover_width": 208,
	  "music.cover_height": 117,
	  "desktop.wallpaper.img": "/home/wilwe/.hyprland.conf/wallpapers/winter.jpg",
	  "desktop.wallpaper.transition": "--transition-type grow --invert-y --transition-pos 1000,215",
	  "dashboard.bg": "linear-gradient",
	  "dashboard.bg_color": "lighten($accent, 10), lighten($bg-color,10), $bg-color",
  })
];
