#!/bin/bash
while [ 0 == 0 ]; do
m1=$(playerctl metadata title)
sleep 1
m2=$(playerctl metadata title)
if [ "$m1" != "$m2" ] && [ "$m2" != "Główna - YouTube" ] && [ "$m2" != "Brave" ] && [ "$m2" != "- YouTube" ]; then
	ags -t info
	sleep 4
	ags -t info
fi
done
