#!/bin/bash
sleep 1
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal
killall xdg-desktop-portal-gtk
/usr/lib/xdg-desktop-portal-hyprland & /usr/lib/xdg-desktop-portal-gtk & /usr/lib/xdg-desktop-portal-wlr & /usr/lib/xdg-desktop-portal
