#!/usr/bin/env python3
import os, subprocess, argparse
parser = argparse.ArgumentParser()
parser.add_argument("-s", "--sddm", help="Set sddm conf from /tmp", action=argparse.BooleanOptionalAction)
parser.add_argument("-g", "--grub", help="Set grub conf from /tmp", action=argparse.BooleanOptionalAction)
parser.add_argument("-p", "--starship", help="Set starship conf from /tmp", action=argparse.BooleanOptionalAction)
parser.add_argument("-k", "--kitty", help="Set kitty conf from /tmp", action=argparse.BooleanOptionalAction)
parser.add_argument("-v", "--vim", help="Set vim conf from /tmp", action=argparse.BooleanOptionalAction)
parser.add_argument("-u", "--update", help="update setup file")
args = parser.parse_args()
if args.sddm != None:
    subprocess.Popen(["sudo", "cp", "-f", "-T", "/tmp/ags/sddm.conf", "/etc/sddm.conf"])
if args.grub != None:
    subprocess.Popen(["sudo", "cp", "-f", "-T", "/tmp/ags/grub.conf", "/etc/default/grub"])
    os.system("sudo grub-mkconfig > /boot/grub/grub.cfg")
if args.starship != None:
    subprocess.Popen(["cp", "-f", "/tmp/ags/starship.conf", "/home/wilwe/.config/starship.toml"])
if args.kitty != None:
    subprocess.Popen(["cp", "-f", "/tmp/ags/kitty.conf", "/home/wilwe/.config/kitty/kitty.conf"])
if args.vim != None:
    subprocess.Popen(["cp", "-f", "-T", "/tmp/ags/vim.vim", "/home/wilwe/.vim/colors/ags.vim"]) 
    subprocess.Popen(["cp", "-f", "-T", "/tmp/ags/airline.vim", "/home/wilwe/.vim/autoload/airline/themes/ags.vim"])
