#!/bin/bash
w1=$(cat /sys/class/net/wlan0/statistics/tx_bytes)
e1=$(cat /sys/class/net/eth0/statistics/tx_bytes)
sleep 1
w2=$(cat /sys/class/net/wlan0/statistics/tx_bytes)
e2=$(cat /sys/class/net/eth0/statistics/tx_bytes)
sum=$((w2+e2-w1-e2))
if [ $sum -ge 1000 ]; then
  if [ $sum -ge 1000000 ]; then
    if [ $sum -ge 1000000000 ]; then
      echo "$((sum / 1000000000))GB/s"
      exit
    fi
    echo "$((sum / 1000000))MB/s"
    exit
  fi
  echo "$((sum / 1000))KB/s"
else
  echo "${sum}B/s"
fi
